In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
odd_number_list = [1,3,5,7]

In [4]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [5]:
two_dim_list = [[1,1,1],[2,2,2],[3,3,3]]

In [8]:
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

Shift + Tab чтобы показать подсказку

In [10]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

np.linspace() равномерно распределенное множество, расстояние одинаково

In [20]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.eye(9) #единичная матрица

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.randn(9) # количество чисел которые нормально распределены

array([ 1.2757857 , -0.39570321, -0.84359862,  0.62663433,  0.16982842,
        0.16337766, -0.98033014,  0.95147055, -1.57759566])

In [29]:
np.random.randn(3,4) # тоже самое только для матриц

array([[ 1.0286678 , -1.2743243 , -0.112618  , -0.16462653],
       [ 1.14275985,  0.45122976, -0.67760352, -1.18909625],
       [-0.58480168, -1.05433144,  0.0766615 , -2.6392385 ]])

In [32]:
np.random.randint(0,50,2)

array([35, 10])

In [35]:
rand_arr = np.random.randint(0,50,20)

In [37]:
second_arr = np.arange(20)

In [39]:
rand_arr.reshape(4,5) # из вектора сделать матрицу

array([[28, 32, 20, 31,  2],
       [39, 42, 24, 48,  9],
       [36, 39, 26, 28, 13],
       [ 7,  4,  4, 25, 17]])

rand_arr.reshape(5,5) Тут будет ошибка, т.к. не хватит элементов

In [41]:
second_arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
second_arr.max()

19

In [43]:
second_arr.min()

0

In [46]:
rand_arr.argmax() # ключ максимального элемента

8

In [48]:
rand_arr.argmin() # ключ минимального элемента

4

In [49]:
second_arr.shape # одномерный масив с 20 элементами

(20,)

In [51]:
reshaped_arr = second_arr.reshape(2,10)

In [52]:
reshaped_arr.shape

(2, 10)