In [1]:
import numpy as np

In [2]:
int_arr = np.random.randint(0,10,10)

In [3]:
int_arr

array([7, 3, 3, 6, 5, 8, 6, 6, 3, 5])

In [4]:
int_arr[0]

7

In [5]:
int_arr[9]

5

In [6]:
int_arr[1:3]

array([3, 3])

In [7]:
int_arr[:]

array([7, 3, 3, 6, 5, 8, 6, 6, 3, 5])

In [8]:
int_arr[4:]

array([5, 8, 6, 6, 3, 5])

In [9]:
int_arr[4:10] = 10

In [10]:
int_arr

array([ 7,  3,  3,  6, 10, 10, 10, 10, 10, 10])

In [12]:
new_arr = int_arr[:4]

In [13]:
new_arr[2:] = 7

In [14]:
new_arr

array([7, 3, 7, 7])

In [15]:
int_arr # обрати внимание! по ссылочке данные 

array([ 7,  3,  7,  7, 10, 10, 10, 10, 10, 10])

In [18]:
arr = np.arange(0,10)

In [19]:
new_arr = arr.copy() # именно скопировать, т.е. после изменения new_arr массив arr не изменится

In [20]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
new_arr[:] = 0

In [22]:
new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Массивы можно сравнивать

In [24]:
arr > 3 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
bool_arr = arr > 6 

In [26]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [28]:
arr[bool_arr] # где значения True

array([7, 8, 9])

In [29]:
bool_arr > 0

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([7, 8, 9])

In [32]:
arr[ arr > 5 ]

array([6, 7, 8, 9])

In [33]:
arr [ arr % 2 == 0]

array([0, 2, 4, 6, 8])