In [1]:
import numpy as np

In [2]:
two_dim_array = np.arange(12).reshape(3,4)

In [4]:
two_dim_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
two_dim_array[1][1]

5

In [6]:
two_dim_array[2][1:]

array([ 9, 10, 11])

In [7]:
two_dim_array[2][:1]

array([8])

In [8]:
two_dim_array[1,1]

5

In [18]:
two_dim_array[:2][2:] #!!!

array([], shape=(0, 4), dtype=int32)

In [20]:
two_dim_array[:2,2:] #!!!

array([[2, 3],
       [6, 7]])

In [21]:
two_dim_array[two_dim_array > 4]

array([ 5,  6,  7,  8,  9, 10, 11])